import {
  WebSocketGateway,
  SubscribeMessage,
  MessageBody,
  WebSocketServer,
  OnGatewayConnection,
  OnGatewayDisconnect,
} from '@nestjs/websockets';
import type { Server } from 'sockjs';
import { SockjsAdapter } from './sockjs.adapter';

@WebSocketGateway()
export class AppWebsocketGateway implements OnGatewayConnection, OnGatewayDisconnect {
  @WebSocketServer()
  server: Server;

  // Track connected clients
  private clients = new Set<any>();

  handleConnection(client: any) {
    this.clients.add(client);
    console.log(`[WebSocket] Client connected`);
  }

  handleDisconnect(client: any) {
    this.clients.delete(client);
    console.log(`[WebSocket] Client disconnected`);
  }

  // Handle incoming chat messages sent to /app/chat
  @SubscribeMessage('/chat')
  handleChat(@MessageBody() data: any): any {
    console.log('[WebSocket] Received message:', data);

    // Format the response as a STOMP MESSAGE frame to /topic/messages
    const frame = SockjsAdapter.formatStompFrame(
      'MESSAGE',
      { destination: '/topic/messages', 'content-type': 'application/json' },
      typeof data === 'string' ? data : JSON.stringify(data),
    );

    // Broadcast to all connected clients
    this.broadcast(frame);
  }

  // Also handle STOMP CONNECTED pseudo-messages generated by the adapter
  @SubscribeMessage('__stomp_command')
  handleStompCommand(data: any): any {
    if (data && data.__stomp_command === 'CONNECTED') {
      return SockjsAdapter.formatStompFrame('CONNECTED', data.headers, data.body);
    }
  }

  private broadcast(message: string) {
    for (const client of this.clients) {
      if (client.write) {
        client.write(message);
      }
    }
  }
}
